### ISSUE TITLE
"ip help" doesn't work

### ISSUE THREAD

**Issue by johnlinp** [brona/iproute2mac#27] opened 2018-09-12 15:31 UTC
Version: v1.2.1

I would like to show the help text by typing `ip help`, but saw the following error:

```
$ip help
Object "help" is unknown, try "ip help".
```

**Comment by SimonTate** [comment] 2018-10-21 09:56
@brona, @johnlinp,

This is a duplicate of #18. This is fixed and just requires update of homebrew repo by @brona.

**Closed** 2018-10-21 10:42 UTC
Labels: duplicate
